/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "file_transfer.h"

bool_t
xdr_filename_t (XDR *xdrs, filename_t *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_filedata_t (XDR *xdrs, filedata_t *objp)
{
	register int32_t *buf;

	 if (!xdr_bytes (xdrs, (char **)&objp->filedata_t_val, (u_int *) &objp->filedata_t_len, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_file_result (XDR *xdrs, file_result *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_filedata_t (xdrs, &objp->data))
		 return FALSE;
	return TRUE;
}
