/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _FILE_TRANSFER_H_RPCGEN
#define _FILE_TRANSFER_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXFILESIZE 1048576

typedef char *filename_t;

typedef struct {
	u_int filedata_t_len;
	char *filedata_t_val;
} filedata_t;

struct file_result {
	int status;
	filedata_t data;
};
typedef struct file_result file_result;

#define FILE_TRANSFER_PROG 0x31234567
#define FILE_TRANSFER_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define GET_FILE 1
extern  file_result * get_file_1(filename_t *, CLIENT *);
extern  file_result * get_file_1_svc(filename_t *, struct svc_req *);
extern int file_transfer_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define GET_FILE 1
extern  file_result * get_file_1();
extern  file_result * get_file_1_svc();
extern int file_transfer_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_filename_t (XDR *, filename_t*);
extern  bool_t xdr_filedata_t (XDR *, filedata_t*);
extern  bool_t xdr_file_result (XDR *, file_result*);

#else /* K&R C */
extern bool_t xdr_filename_t ();
extern bool_t xdr_filedata_t ();
extern bool_t xdr_file_result ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_FILE_TRANSFER_H_RPCGEN */
